# action.yml
name: 'diff ctx'
description: 'Diff Context'
inputs:
  lang:
    description: 'language of your repo'
    required: true
    default: 'python'
  after_sha:
    description: 'after sha'
    required: true
    default: ${{ github.sha }}
  before_sha:
    description: 'before sha'
    required: true
    default: ${{ github.event.before }}
  repo_token:
    description: "A GitHub token for API access. Defaults to {{ github.token }}."
    default: "${{ github.token }}"
    required: false
  issue_number:
    description: "issue number"
    default: "${{ github.event.number }}"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lang }}
    - ${{ inputs.before_sha }}
    - ${{ inputs.after_sha }}
    - ${{ inputs.repo_token }}
    - ${{ inputs.issue_number }}
