# action.yml
name: 'diff ctx'
description: 'Diff Context'
inputs:
  lang:
    description: 'language of your repo'
    required: true
    default: 'python'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lang }}
